{
 "title": "BentoFunction",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(bentoml_api_server_request_total, namespace)"
    }
   },
   {
    "name": "bento_function",
    "label": "BentoFunction",
    "query": {
     "query": "label_values(bentoml_api_server_request_total, yatai_ai_bento_function)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "In-Progress Request Volume",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bentoml_api_server_request_in_progress{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"})",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\"}[2m])), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code!~\"[4-5].*\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m])) / sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "In-Progress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (bentoml_api_server_request_in_progress{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(exported_endpoint) (bentoml_api_server_request_in_progress{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"})",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\"}[2m])), 0.001)",
     "legendFormat": "Total"
    },
    {
     "expr": "round(sum by(exported_endpoint) (irate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\"}[2m])), 0.001)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Request Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code!~\"[4-5].*\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m])) / sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code!~\"[4-5].*\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m])) by (exported_endpoint) / sum(rate(bentoml_api_server_request_total{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", exported_endpoint!=\"/\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\", exported_endpoint!~\"/static_content/.*\"}[2m])) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Request Percentile Response Times",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(bentoml_api_server_request_duration_seconds_bucket{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code=~\"2.*\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\"}[2m])) by (le, exported_endpoint))",
     "legendFormat": "{{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(bentoml_api_server_request_duration_seconds_bucket{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code=~\"2.*\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\"}[2m])) by (le, exported_endpoint))",
     "legendFormat": "{{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(bentoml_api_server_request_duration_seconds_bucket{namespace=\"$namespace\", yatai_ai_bento_function=~\"$bento_function\", http_response_code=~\"2.*\", exported_endpoint!=\"/\", exported_endpoint!~\"/static_content/.*\", exported_endpoint!=\"/docs.json\", exported_endpoint!=\"/robots.txt\"}[2m])) by (le, exported_endpoint))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))",
     "legendFormat": "All Received"
    },
    {
     "expr": "- (sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "All Sent"
    },
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))",
     "legendFormat": "{{workload}} Sent"
    },
    {
     "expr": "- (sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}} Received"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on (namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-.*)?\", workload_type=\"deployment\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on (namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-.*)?\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on (namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on (namespace, pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}) by (pod))\n"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}\n) by (pod)\n"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"}))\n",
     "legendFormat": "Total"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"[[bento_function]](-runner-[0-9]+)?\", workload_type=\"deployment\"})\nby (workload))\n",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}