run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # include test files or not, default is true
  tests: true

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  # make issues output unique by line, default is true
  uniq-by-line: true


linters-settings:
  goimports:
    local-prefixes: github.com/bentoml
  govet:
    settings:
      printf:
        funcs:
          - (github.com/sirupsen/logrus).Infof
          - (github.com/sirupsen/logrus).Warnf
          - (github.com/sirupsen/logrus).Debugf
          - (github.com/sirupsen/logrus).Errorf
          - (github.com/sirupsen/logrus).Fatalf
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: false
  presets:
    - bugs
    - unused
  disable:
    - unused
    - scopelint
  enable:
    - bodyclose
    - deadcode
    - varcheck
    - ineffassign
    - exportloopref
    - sqlclosecheck
    - structcheck
    - typecheck
    - gofmt
    - unconvert
    - staticcheck
    - govet
    - gosimple
    - unparam
    - gocritic
    - goconst
    - goimports
    - dogsled
    - whitespace
    - misspell
    - rowserrcheck
