# syntax = docker/dockerfile:1-experimental

FROM golang:1.20-alpine as base

WORKDIR /src
ENV CGO_ENABLED=0
COPY go.* ./
RUN --mount=type=cache,target=/go/pkg/mod \
  go mod download

FROM base AS build
ARG VERSION_BUILDFLAGS
RUN --mount=target=. \
  --mount=type=cache,target=/root/.cache/go-build \
  --mount=type=cache,target=/go/pkg/mod \
  go build -ldflags "${VERSION_BUILDFLAGS}" -o /bin/api-server ./api-server/main.go

FROM scratch AS export
COPY --from=build /bin/api-server .
