in_cluster: false

server:  # the server config section
  enable_https: false  # if the yatai is deployed as an https server, set it to ture
  port: 7777  # the server port
  session_secret_key: PleaseReplaceIt!  # the cookie secret, must modify and persist it when deployed to the production environment
  migration_dir: ./api-server/db/migrations  # the migrations sql files directory

postgresql:  # the database config section
  host: localhost
  port: 5432
  user: yetone
  password: ''
  database: yatai

oauth:
  github:  # https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app
    client_id: ''
    client_secret: ''
