in_cluster: false

server:  # the server config section
  enable_https: false  # if the yatai is deployed as an https server, set it to true
  port: 7777  # the server port
  session_secret_key: PleaseReplaceIt!  # the cookie secret, must modify and persist it when deployed to the production environment
  migration_dir: ./api-server/db/migrations  # the migrations sql files directory

postgresql:  # the database config section
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: yatai

s3:
  endpoint: s3.us-west-2.amazonaws.com
  region: us-west-2
  bucket_name: <YOUR BUCKET NAME>
  secure: true

initialization_token: 12345
