apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai.fullname" . }}
  labels:
  {{- include "yatai.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    in_cluster: true

    server:  # the server config section
      enable_https: false  # if the yatai is deployed as an https server, set it to ture
      port: 7777  # the server port
      session_secret_key: {{ include "yatai.sessionSecretKey" . }}  # the cookie secret, must modify and persist it when deployed to the production environment
      migration_dir: /app/db/migrations  # the migrations sql files directory

    {{- (ternary "" (toYaml .Values.config) (empty .Values.config)) | nindent 4 }}
