apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yatai-deployment-comp-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yatai-deployment-comp-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-deployment-comp-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
