apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"yatai-deployment-comp-operator-manager-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"yatai-deployment-comp-operator-manager-role"},"subjects":[{"kind":"ServiceAccount","name":"yatai-deployment-comp-operator-controller-manager","namespace":"yatai-deployment-comp-operator-system"}]}
  name: yatai-deployment-comp-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "yatai-deployment-comp-operator.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-deployment-comp-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
