apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai-deployment-comp-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yatai-deployment-comp-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_ENDPOINT: {{ .Values.yatai.endpoint }}
  YATAI_API_TOKEN: {{ .Values.yatai.apiToken }}
  YATAI_CLUSTER_NAME: {{ .Values.yatai.clusterName }}

